Repository InvictoProjects/Streaming_Platform, pull requests merged in 2021-03, with the labels that each got.

#26 Did some refactoring and renamed findByEmailAddress to findByEmail
  README.md
  src/main/java/com/invicto/streaming_platform/StreamingPlatformApplication.java
  src/main/java/com/invicto/streaming_platform/config/CustomAuthenticationProvider.java
  src/main/java/com/invicto/streaming_platform/config/WebSecurityConfig.java
  src/main/java/com/invicto/streaming_platform/persistence/model/User.java
  src/main/java/com/invicto/streaming_platform/persistence/repository/UserRepository.java
  src/main/java/com/invicto/streaming_platform/services/UserService.java
  src/main/java/com/invicto/streaming_platform/services/impl/UserServiceImpl.java
  src/main/java/com/invicto/streaming_platform/web/controller/HomeController.java
  src/main/java/com/invicto/streaming_platform/web/controller/UserController.java
  src/test/java/com/invicto/streaming_platform/StreamingPlatformApplicationTests.java
Labels: enhancement

#29 Implement createUser, findById methods
  src/main/java/com/invicto/streaming_platform/services/UserService.java
  src/main/java/com/invicto/streaming_platform/services/impl/UserServiceImpl.java
Labels: enhancement

#32 Implement updateUser and findAll methods. Add tests for findAll, findByLogin and updateUser methods
  src/main/java/com/invicto/streaming_platform/services/UserService.java
  src/main/java/com/invicto/streaming_platform/services/impl/UserServiceImpl.java
  src/test/java/com/invicto/streaming_platform/services/impl/UserServiceImplTest.java
Labels: enhancement, testing

#36 Add tests for used UserRepository methods and createUser, findById UserService methods
  src/main/java/com/invicto/streaming_platform/persistence/model/User.java
  src/test/java/com/invicto/streaming_platform/persistence/repository/UserRepositoryTest.java
  src/test/java/com/invicto/streaming_platform/services/impl/UserServiceImplTest.java
Labels: testing

#37 Solved bug in test
  src/test/java/com/invicto/streaming_platform/services/impl/UserServiceImplTest.java
Labels: bug

#40 Register update
  src/main/java/com/invicto/streaming_platform/web/controller/UserController.java
  src/main/resources/static/styles/registrationStyles.css
  src/main/resources/templates/signup.html
Labels: design, enhancement

#41 Add reCaptcha v2 to Registration page
  src/main/java/com/invicto/streaming_platform/captcha/CaptchaService.java
  src/main/java/com/invicto/streaming_platform/captcha/CaptchaServiceImpl.java
  src/main/java/com/invicto/streaming_platform/captcha/CaptchaSettings.java
  src/main/java/com/invicto/streaming_platform/captcha/ErrorCode.java
  src/main/java/com/invicto/streaming_platform/captcha/GoogleResponse.java
  src/main/java/com/invicto/streaming_platform/captcha/ReCaptchaInvalidException.java
  src/main/java/com/invicto/streaming_platform/web/controller/UserController.java
  src/main/resources/application.properties
  src/main/resources/templates/signup.html
Labels: feature

#42 Add CSS to some html pages
  src/main/java/com/invicto/streaming_platform/web/controller/AccountController.java
  src/main/resources/templates/error.html
  src/main/resources/templates/forgot_password.html
  src/main/resources/templates/login.html
  src/main/resources/templates/message.html
  src/main/resources/templates/reset_password.html
Labels: design, enhancement

#47 Add Video Model, Video Repository and Service
  src/main/java/com/invicto/streaming_platform/persistence/model/Video.java
  src/main/java/com/invicto/streaming_platform/persistence/repository/VideoRepository.java
  src/main/java/com/invicto/streaming_platform/services/VideoService.java
  src/main/java/com/invicto/streaming_platform/services/impl/UserServiceImpl.java
  src/main/java/com/invicto/streaming_platform/services/impl/VideoServiceImpl.java
  src/test/java/com/invicto/streaming_platform/services/impl/UserServiceImplTest.java
Labels: feature
