Repository InvictoProjects/Streaming_Platform, pull requests merged in 2021-05, with the labels that each got.

#62 Replace get tag step in docker Action with Release tag
  .github/workflows/docker.yml
  docker-compose-springboot.yml
  docker-compose.yml
  docker/jar/Dockerfile
  docker/springboot/Dockerfile
Labels: ci

#63 Preview uploading
  src/main/java/com/invicto/streaming_platform/services/impl/FileServiceImpl.java
  src/main/java/com/invicto/streaming_platform/web/controller/FileController.java
  src/main/java/com/invicto/streaming_platform/web/dto/VideoDto.java
  src/main/resources/application.properties
  src/main/resources/static/styles/uploadStyles.css
  src/main/resources/templates/upload.html
Labels: feature

#64 Add captcha and password visibility button to login page
  src/main/java/com/invicto/streaming_platform/captcha/CaptchaAspect.java
  src/main/java/com/invicto/streaming_platform/captcha/CaptchaService.java
  src/main/java/com/invicto/streaming_platform/captcha/CaptchaServiceImpl.java
  src/main/java/com/invicto/streaming_platform/captcha/RequiresCaptcha.java
  src/main/java/com/invicto/streaming_platform/security/CustomUserDetailsService.java
  src/main/java/com/invicto/streaming_platform/web/controller/UserController.java
  src/main/resources/static/js/login.js
  src/main/resources/static/js/reCaptcha.js
  src/main/resources/static/styles/footer.css
  src/main/resources/static/styles/header.css
  src/main/resources/static/styles/index.css
  src/main/resources/static/styles/login.css
  src/main/resources/templates/fragments/captcha.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: design, enhancement

#65 Video commenting
  src/main/java/com/invicto/streaming_platform/persistence/model/Comment.java
  src/main/java/com/invicto/streaming_platform/services/CommentService.java
  src/main/java/com/invicto/streaming_platform/services/impl/CommentServiceImpl.java
  src/main/java/com/invicto/streaming_platform/web/controller/VideoController.java
  src/main/resources/static/js/video.js
  src/main/resources/static/styles/video.css
  src/main/resources/templates/video.html
Labels: feature

#67 Add video cards to home page
  src/main/java/com/invicto/streaming_platform/persistence/repository/VideoRepository.java
  src/main/java/com/invicto/streaming_platform/services/FileService.java
  src/main/java/com/invicto/streaming_platform/services/VideoService.java
  src/main/java/com/invicto/streaming_platform/services/impl/FileServiceImpl.java
  src/main/java/com/invicto/streaming_platform/services/impl/VideoServiceImpl.java
  src/main/java/com/invicto/streaming_platform/web/config/WebSecurityConfig.java
  src/main/java/com/invicto/streaming_platform/web/controller/HomeController.java
  src/main/resources/static/images/thumbnail.png
  src/main/resources/static/js/index.js
  src/main/resources/static/styles/header.css
  src/main/resources/static/styles/index.css
  src/main/resources/static/styles/video_cards.css
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/video_cards.html
Labels: design, feature
